# Generated by Django 4.1.3 on 2022-12-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='SMARTname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
